{
 "title": "Jingtum Blockchain Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Jingtum Nodes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "jt_total_node_count", "legendFormat": "Total Node" },
    { "expr": "jt_online_node_count", "legendFormat": "Online Node" },
    { "expr": "jt_consensus_node_count", "legendFormat": "Consensus Node" }
   ]
  },
  {
   "title": "Block Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "jt_block_number", "legendFormat": "Block Height" },
    { "expr": "jt_current_block_tx_count", "legendFormat": "Transaction Count" }
   ]
  },
  {
   "title": "TPS Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "jt_average_tps", "legendFormat": "Total Average Tps" },
    { "expr": "jt_current_block_tps", "legendFormat": "Current Block Tps" },
    { "expr": "jt_current_minute_tps", "legendFormat": "Last Minute Tps" },
    { "expr": "jt_current_hour_tps", "legendFormat": "Last Hour Tps" },
    { "expr": "jt_current_day_tps", "legendFormat": "Last Day Tps" },
    { "expr": "jt_current_week_tps", "legendFormat": "Last Week Tps" }
   ]
  },
  {
   "title": "TPS Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jt_average_tps", "legendFormat": "Total Average Tps" },
    { "expr": "jt_current_block_tps", "legendFormat": "Current Block Tps" },
    { "expr": "jt_current_minute_tps", "legendFormat": "Last Minute Tps" },
    { "expr": "jt_current_hour_tps", "legendFormat": "Last Hour Tps" },
    { "expr": "jt_current_day_tps", "legendFormat": "Last Day Tps" },
    { "expr": "jt_current_week_tps", "legendFormat": "Last Week Tps" }
   ]
  }
 ]
}