{
 "title": "Jingtum Blockchain Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Block Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    { "expr": "jt_block_number", "legendFormat": "Block Height" },
    { "expr": "jt_current_block_tx_count", "legendFormat": "Tx Count" }
   ]
  },
  {
   "title": "Jingtum Net",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "targets": [
    { "expr": "jt_total_node_count", "legendFormat": "Total " },
    { "expr": "jt_online_node_count", "legendFormat": "Online " },
    { "expr": "jt_consensus_node_count", "legendFormat": "Consensus " }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "jt_block_number{job=\"jt_monitor\"}"
    }
   ]
  },
  {
   "title": "TPS Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "expr": "jt_average_tps", "legendFormat": "Total Average Tps" },
    { "expr": "jt_current_block_tps", "legendFormat": "Last Block Tps" },
    { "expr": "jt_current_3blocks_tps", "legendFormat": "Last 3 Blocks Tps" },
    { "expr": "jt_current_minute_tps", "legendFormat": "Last Minute Tps" },
    { "expr": "jt_current_hour_tps", "legendFormat": "Last Hour Tps" },
    { "expr": "jt_current_day_tps", "legendFormat": "Last Day Tps" },
    { "expr": "jt_current_week_tps", "legendFormat": "Last Week Tps" }
   ]
  },
  {
   "title": "TPS Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jt_average_tps", "legendFormat": "Total Average Tps" },
    { "expr": "jt_current_block_tps", "legendFormat": "Last Block Tps" },
    { "expr": "jt_current_3blocks_tps", "legendFormat": "Last 3 Blocks Tps" },
    { "expr": "jt_current_minute_tps", "legendFormat": "Last Minute Tps" },
    { "expr": "jt_current_hour_tps", "legendFormat": "Last Hour Tps" },
    { "expr": "jt_current_day_tps", "legendFormat": "Last Day Tps" },
    { "expr": "jt_current_week_tps", "legendFormat": "Last Week Tps" }
   ]
  }
 ]
}